### ISSUE TITLE
PropTypes warning on upgrading to React 15.5

### ISSUE THREAD

**Issue by vijayst** [RosyTucker/react-feature-toggles#2]
In React 15.5, PropTypes must be imported from prop-types package. The following code is throwing a warning:

```js
import React, { PropTypes, Component } from 'react';
```

Should I do a PR? Thanks.

**Comment by RosyTucker** [comment]
Sure absolutely

**Comment by vijayst** [comment]
Created PR #3

**Comment by RosyTucker** [comment]
Released in 2.0.3. Thanks!
