### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by barrymichaeldoyle** [RosyTucker/react-feature-toggles#7]
Hey @RosyTucker , just noticed that the latest update hasn't been published to npm. Could you do that when you get a chance. Thanks!

**Comment by rose-improbable** [comment]
Hey,

It's running through CI now as 3.0.2

Thanks

**Comment by RosyTucker** [comment]
Hey,

It's running through CI now as 3.0.2

Thanks

**Comment by barrymichaeldoyle** [comment]
Thanks @RosyTucker :)
